import { Inter as FontSans } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

import { cn } from "@/lib/utils";
import Link from "next/link";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <nav className="flex flex-row items-center gap-5 m-5 p-2 bg-zinc-200 rounded-md">
          <Link href="/" className="text-orange-800 font-bold text-xl">
            Nebula Blogs
          </Link>
          <Link href="/">Home</Link>
          <Link href="/create-blog">Create New Blog</Link>
        </nav>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
